### Runge Kutta 4th order method (proof of 5th order local convergence in mathematica notebook)

In [2]:
def dydx(x, y): 
    return (y/4)*(1-(y/20)) 

def rungeKutta(x0, y0, x, h, fnc): 
    n = (int)((x - x0)/h)   
    y = y0 
    for i in range(1, n + 1): 
        k1 = h * fnc(x0, y) 
        k2 = h * fnc(x0 + 0.5 * h, y + 0.5 * k1) 
        k3 = h * fnc(x0 + 0.5 * h, y + 0.5 * k2) 
        k4 = h * fnc(x0 + h, y + k3) 
        y = y + (1.0 / 6.0)*(k1 + 2 * k2 + 2 * k3 + k4) 
        print(y)
        x0 = x0 + h 
    return y 
# Driver method 
x0 = 0
y = 1
x = 4
h = 0.2
rungeKutta(x0, y, x, h, dydx) 
  

1.0485829944673644
1.0993897227515854
1.1525084697069707
1.2080296941737445
1.266045944062374
1.3266517534612325
1.3899435203136021
1.4560193631813456
1.5249789555961606
1.5969233364974498
1.6719546952710274
1.7501761299377632
1.8316913770986514
1.9166045123255722
2.0050196197981554
2.0970404301296135
2.192769925501099
2.2923099114377994
2.39576055481316
2.503219887962471


2.503219887962471

### 4th order system of differential equations reduced to single order system

In [4]:
import numpy as np
def f(x, y):
    #y must be a vector now
    return np.array([[y[1]], [-2/x * y[0] * y[1]]])

x0 = 1
y = np.array([[1/2], [1/4]])
x = 2
h = 0.5
rungeKutta(x0, y, x, h, f) 

[[[[[[0.68603027]
     [0.35619303]]

    [[0.64436361]
     [0.31452637]]]


   [[[0.54748861]
     [0.30931803]]

    [[0.50582194]
     [0.26765137]]]]



  [[[[0.55384928]
     [0.30049642]]

    [[0.51218262]
     [0.25882975]]]


   [[[0.41530762]
     [0.25362142]]

    [[0.37364095]
     [0.21195475]]]]]




 [[[[[0.6369877 ]
     [0.33192457]]

    [[0.59532103]
     [0.2902579 ]]]


   [[[0.49844603]
     [0.28504957]]

    [[0.45677936]
     [0.2433829 ]]]]



  [[[[0.50480671]
     [0.27622795]]

    [[0.46314004]
     [0.23456128]]]


   [[[0.36626504]
     [0.22935295]]

    [[0.32459837]
     [0.18768628]]]]]]
[[[[[[[[[[0.95720901]
         [0.51251322]]

        [[0.90221626]
         [0.45426091]]]


       [[[0.77288729]
         [0.4469461 ]]

        [[0.71660136]
         [0.38815541]]]]



      [[[[0.78144396]
         [0.43453954]]

        [[0.72522029]
         [0.37564534]]]


       [[[0.5928809 ]
         [0.36824885]]

        [[0.53523227]
         [0.308

array([[[[[[[[[[0.95720901],
               [0.51251322]],

              [[0.90221626],
               [0.45426091]]],


             [[[0.77288729],
               [0.4469461 ]],

              [[0.71660136],
               [0.38815541]]]],



            [[[[0.78144396],
               [0.43453954]],

              [[0.72522029],
               [0.37564534]]],


             [[[0.5928809 ],
               [0.36824885]],

              [[0.53523227],
               [0.30879276]]]]],




           [[[[[0.89357198],
               [0.47980582]],

              [[0.83828682],
               [0.42137177]]],


             [[[0.70824335],
               [0.41403386]],

              [[0.65163448],
               [0.35505519]]]],



            [[[[0.71684848],
               [0.40158797]],

              [[0.66030334],
               [0.3425046 ]]],


             [[[0.52717813],
               [0.33508406]],

              [[0.46917425],
               [0.27543233]]]]]],





          